spring:
  application:
    name: activity-service
  mongodb:
      uri: mongodb+srv://kapratwarajay:Admin123@cluster0.fpl7zfu.mongodb.net/fitness_activity

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true